<<<<<<< HEAD
DATA = "Med" #or "MNIST"

# Training parameters
=======
# --- TRAINING PARAMETERS ---
>>>>>>> 98324aa3cd5773dae222a4dc06be7ade35fdf0ee
NR_CLIENTS = 3
LR = 0.01
CLIENT_EPOCHS = 6
NR_TRAINING_ITERATIONS = 3
<<<<<<< HEAD

if DATA == "Med":
    BATCH_SIZE = 2
elif DATA == "MNIST":
    BATCH_SIZE = 128
=======
BATCH_SIZE = 128
# Number of client training epochs.
>>>>>>> 98324aa3cd5773dae222a4dc06be7ade35fdf0ee
EPOCHS = 20

# --- DIFFERENTIAL PRIVACY PARAMETERS ---
MAX_GRAD_NORM = 1.2
EPSILON = 60.0

EPSILON_TRAINING_ITERATION = EPSILON / NR_TRAINING_ITERATIONS
# DELTA = 1e-5

VIRTUAL_BATCH_SIZE = 2*BATCH_SIZE

assert VIRTUAL_BATCH_SIZE % BATCH_SIZE == 0  # VIRTUAL_BATCH_SIZE should be divisible by BATCH_SIZE
N_ACCUMULATION_STEPS = int(VIRTUAL_BATCH_SIZE / BATCH_SIZE)
