# --- TRAINING PARAMETERS ---
NR_CLIENTS = 3
LR = 0.01
CLIENT_EPOCHS = 6
NR_TRAINING_ITERATIONS = 3
BATCH_SIZE = 128
# Number of client training epochs.
EPOCHS = 20

# --- DIFFERENTIAL PRIVACY PARAMETERS ---
MAX_GRAD_NORM = 1.2
EPSILON = 60.0
EPSILON_TRAINING_ITERATION = EPSILON / NR_TRAINING_ITERATIONS
# DELTA = 1e-5

VIRTUAL_BATCH_SIZE = 256
assert VIRTUAL_BATCH_SIZE % BATCH_SIZE == 0  # VIRTUAL_BATCH_SIZE should be divisible by BATCH_SIZE
N_ACCUMULATION_STEPS = int(VIRTUAL_BATCH_SIZE / BATCH_SIZE)
