# Training parameters
NR_CLIENTS = 1
LR = 0.01
CLIENT_EPOCHS = 1
NR_TRAINING_ITERATIONS = 3
BATCH_SIZE = 128
EPOCHS = 20

# Differential privacy parameters
MAX_GRAD_NORM = 1.2
EPSILON = 60.0
EPSILON_TRAINING_ITERATION = EPSILON / NR_TRAINING_ITERATIONS
# DELTA = 1e-5

VIRTUAL_BATCH_SIZE = 256
assert VIRTUAL_BATCH_SIZE % BATCH_SIZE == 0  # VIRTUAL_BATCH_SIZE should be divisible by BATCH_SIZE
N_ACCUMULATION_STEPS = int(VIRTUAL_BATCH_SIZE / BATCH_SIZE)
